export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const BIND_TRANSACTION_MODEL = "BIND_TRANSACTION_MODEL";
export const CUSTOM_ERROR = "CUSTOM_ERROR";
export const RESET_AUTHENTICATION = "RESET_AUTHENTICATION";
export const SAVE_FILTERS = "SAVE_FILTERS";
